# Generated by Django 2.0.5 on 2018-05-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
