# Generated by Django 2.0.5 on 2018-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20180513_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
